ChatEME/ChatEME/urls.py
    # ChatEME - Chat Engine Made Easy
    # Copyright (C) 2023  Florian Dewes

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.urls import path

from . import views
from .models import extract_text_from_html

app_name = 'ChatEME'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:model_id>/', views.ClassifierModelDetail, name='ClassifierModelDetail'),
    path('<int:model_id>/add_CrawlRoot/', views.add_CrawlRoot, name='add_CrawlRoot'),
    path('<int:model_id>/add_QAPair/', views.add_QAPair, name='add_QAPair'),
    path('<int:pk>/update_ClassifierModel/', views.ClassifierModelUpdateView.as_view(), name='update_ClassifierModel'),
    path('add_ClassifierModel/', views.add_ClassifierModel, name='add_ClassifierModel'),
    path('<int:model_id>/crawl_pages/', views.crawl_pages, name='crawl_pages'),
    path('<int:model_id>/clear_pages/', views.clear_pages, name='clear_pages'),
    path('<int:model_id>/extract_text_from_html/', extract_text_from_html, name='extract_text_from_html'),
    path('<int:model_id>/train_model/', views.train_model, name='train_model'),
    path('<int:model_id>/inspect_model/', views.inspect_model, name='inspect_model'),
    path('<int:model_id>/serve_model/', views.serve_model, name='serve_model'),
    path('<int:model_id>/<int:cr_id>/', views.CrawlRootDetail, name='CrawlRootDetail'),
    path('<int:model_id>/<int:cr_id>/delete', views.delete_CrawlRoot, name='delete_CrawlRootDetail'),
    path('<int:model_id>/<int:cr_id>/add_CrawlRule_URLContainsString', views.add_CrawlRule_URLContainsString, name='add_CrawlRule_URLContainsString'),
    path('<int:model_id>/<int:cr_id>/add_CrawlRule_URLNotContainsString', views.add_CrawlRule_URLNotContainsString, name='add_CrawlRule_URLNotContainsString'),   
    path('<int:model_id>/<int:rule_id>/delete_CrawlRule_URLContainsString', views.delete_CrawlRule_URLContainsString, name='delete_CrawlRule_URLContainsString'),
    path('<int:model_id>/<int:rule_id>/delete_CrawlRule_URLNotContainsString', views.delete_CrawlRule_URLNotContainsString, name='delete_CrawlRule_URLNotContainsString'),
    path('<int:model_id>/apply_rules/', views.apply_rules, name='apply_rules'),
    path('<int:model_id>/<int:page_id>/flip_active', views.flip_active, name='flip_active'),
    path('<int:model_id>/<int:page_id>/page_source', views.page_source, name='page_source'),
    path('<int:model_id>/update_QAPair/<int:pk>/', views.QAPairUpdateView.as_view(), name='update_QAPair'),
    path('<int:model_id>/delete_QAPair/<int:pk>/', views.QAPairDeleteView.as_view(), name='delete_QAPair'),    
    path('<int:model_id>/delete_all_QAPairs/', views.delete_all_QAPairs, name='delete_all_QAPairs'),    
    path('<int:model_id>/update_CrawlRoot/<int:pk>/', views.CrawlRootUpdateView.as_view(), name='update_CrawlRoot'),
    path('<int:model_id>/update_WebPage/<int:pk>/', views.WebPageUpdateView.as_view(), name='update_WebPage'),
    path('<int:model_id>/delete_CrawlRoot/<int:pk>/', views.CrawlRootDeleteView.as_view(), name='delete_CrawlRoot'),
    path('<int:model_id>/delete_WebPage/<int:pk>/', views.WebPageDeleteView.as_view(), name='delete_WebPage'),
    path('<int:pk>/delete_ClassifierModel/', views.ClassifierModelDeleteView.as_view(), name='delete_ClassifierModel'),
    path('<int:model_id>/save_model/', views.save_model, name='save_model'),
    path('load_model/', views.load_model, name='load_model'),
    path('<int:model_id>/import_RasaNLUFile/', views.import_RasaNLUFile, name='import_RasaNLUFile'),
    path('<int:model_id>/import_RasaDomainFile/', views.import_RasaDomainFile, name='import_RasaDomainFile'),
    path('<int:model_id>/export_oos2json/', views.export_oos2json, name='export_oos2json'),
    path('<int:model_id>/<int:page_id>/penalize_WebPage/<str:user_input>', views.penalize_WebPage, name='penalize_webpage'),
    path('<int:model_id>/<int:pair_id>/penalize_QAPair/<str:user_input>', views.penalize_QAPair, name='penalize_qapair'),

]

ChatEME/ChatEME_app/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('ChatEME/', include('ChatEME.urls')),
    path('admin/', admin.site.urls),
]

ChatEME/ChatEME/forms.py
    # ChatEME - Chat Engine Made Easy
    # Copyright (C) 2023  Florian Dewes

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.

from django.forms import ModelForm, Form, CharField, FileField

from .models import CrawlRoot, ClassifierModel, QAPair
from .models import CrawlRule_URLNotContainsString, CrawlRule_URLContainsString

class CrawlRootForm(ModelForm):

	class Meta:

		model = CrawlRoot
		fields = ('root_url', 'short_name', 'crawl_depth', 'extract_tags', 
			'focus_tag', 'exclude_tags', 'exclude_in_url_strings')

class CreateModelForm(ModelForm):

	class Meta:

		model = ClassifierModel
		fields = ('name', 'transformer_model_name', 'epochs')


class CrawlRule_URLContainsStringForm(ModelForm):

	class Meta:

		model = CrawlRule_URLContainsString
		fields = ('filter_string',)

class CrawlRule_URLNotContainsStringForm(ModelForm):

	class Meta:

		model = CrawlRule_URLNotContainsString
		fields = ('filter_string',)

class UserInputForm(Form):

     user_input = CharField(label='Input')

class QAPairForm(ModelForm):

	class Meta:

		model = QAPair
		fields = ('intent', 'questions', 'answer', 'penalty_text')

class UploadFileForm(Form):

	file = FileField()

ChatEME/ChatEME/views.py
    # ChatEME - Chat Engine Made Easy
    # Copyright (C) 2023  Florian Dewes

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.

import threading
import ast
from datasets import Dataset
from json import dumps, loads, dump, load
from os import makedirs
from flask import Flask, request
from requests import post

import torch
from transformers import AutoTokenizer, DataCollatorWithPadding
from transformers import TrainingArguments, Trainer
from transformers import AutoModelForSequenceClassification

from django.http import HttpResponse
from django.utils.http import urlencode
from django.template import loader
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

import plotly.graph_objects as go
from plotly.offline import plot

from .models import CrawlRoot, ClassifierModel, WebPage, QAPair
from .models import CrawlRule_URLContainsString, CrawlRule_URLNotContainsString
from .models import bg_crawl
from .scraper import extract_domain

from .forms import CrawlRootForm, CreateModelForm, UserInputForm, QAPairForm
from .forms import CrawlRule_URLContainsStringForm
from .forms import CrawlRule_URLNotContainsStringForm
from .forms import UploadFileForm

from .files import handle_uploaded_nlu_file, handle_uploaded_save_file
from .files import handle_uploaded_domain_file, create_save_file

from datetime import datetime
from urllib.parse import parse_qs

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15" # This has to move somewhere else

# Create your views here.

def index(request):
    """
    index view with models
    """

    models = ClassifierModel.objects.all()    

    context = {
        'models': models,
        'no_models': len(models), 

    }

    template = loader.get_template('ChatEME/index.html')
    return HttpResponse(template.render(context, request))


def ClassifierModelDetail(request, model_id):
    """
    Main view of the App: Model and its children
    """

    models = ClassifierModel.objects.all()

    model = get_object_or_404(ClassifierModel, pk=model_id)
    crawl_roots =  model.crawlroots.all()
    web_pages = model.webpages.all()
    qapairs = model.qapairs.all()
    no_active_webpages = len(model.webpages.filter(active=True))
    no_links_processed_webpages = len(model.webpages.filter(links_processed=True))
    urlcontainsstring = []
    urlnotcontainsstring = []
    no_crawl_rules = 0

    for cr in crawl_roots:
        urlcontainsstring.append(cr.crawlrule_urlcontainsstring.all())
        urlnotcontainsstring.append(cr.crawlrule_urlnotcontainsstring.all())

        no_crawl_rules += cr.crawlrule_urlcontainsstring.all().count() + \
            cr.crawlrule_urlnotcontainsstring.all().count()

    # Plotly
    
    if model.plot_labels != "" and model.plot_parents != "":

        graphs = []

        graphs.append(
            go.Treemap(labels = loads(model.plot_labels),
                    parents = loads(model.plot_parents))
        )

        layout = {
            'title': 'Tree view',
            'height': 1000,
            'width': 1800,
        }

        plot_div = plot({'data': graphs, 'layout': layout}, 
                        output_type='div')

    else:

        plot_div = None

    if len(web_pages) == 0:
        web_pages = None

    context = {
        'model': model,
        'qapairs': qapairs,
        'crawl_roots': crawl_roots,
        'no_crawl_roots': len(crawl_roots),
        'web_pages': web_pages,
        'plt_div': plot_div,
        'models' : models,
        'urlcontainsstring': urlcontainsstring,
        'urlnotcontainsstring': urlnotcontainsstring,
        'no_crawl_rules': no_crawl_rules,
        'no_active_webpages': no_active_webpages,
        'no_links_processed_webpages': no_links_processed_webpages
    }


    template = loader.get_template('ChatEME/ClassifierModelDetail.html')
    return HttpResponse(template.render(context, request))


def add_ClassifierModel(request):
    """
    View for adding a Classifier Model
    """

    if request.method == 'POST':
        form = CreateModelForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.save()

            return redirect ("ChatEME:index")
      
    form = CreateModelForm()
    return render(request, "ChatEME/generic_model_form.html", {'form':form})


def add_CrawlRoot(request, model_id):
    """
    View for adding a CrawlRoot
    """

    if request.method == 'POST':
        form = CrawlRootForm(request.POST)
        if form.is_valid():
            crawl_root = form.save(commit=False)
            crawl_root.classifier_model = ClassifierModel.objects.get(id=
                model_id)
            crawl_root.save()

            domain = extract_domain(crawl_root.root_url)

            CrawlRule_URLContainsString.objects.create(
                crawl_root=CrawlRoot.objects.get(id=crawl_root.id), 
                filter_string=domain
            )

            for exclude_in_url_string in crawl_root.exclude_in_url_strings.split(","):
                CrawlRule_URLNotContainsString.objects.create(
                crawl_root=CrawlRoot.objects.get(id=crawl_root.id), 
                filter_string=exclude_in_url_string
                )



            return redirect ("ChatEME:ClassifierModelDetail", model_id = model_id)

    form = CrawlRootForm()
    return render(request, "ChatEME/generic_model_form.html", {'form':form})


def clear_pages(request, model_id):
    """
    remove all pages from model
    """

    model = get_object_or_404(ClassifierModel, pk=model_id)
    pages = model.webpages.all()

    for page in pages:
        page.delete() 

    model.plot_labels = ""
    model.plot_parents = ""
    model.save()

    return redirect ("ChatEME:ClassifierModelDetail", model_id = model_id)


def CrawlRootDetail(request, model_id, cr_id):
    """
    view for CrawlRootDetail
    """
    cr = CrawlRoot.objects.get(pk=cr_id)
    urlcontainsstring = cr.crawlrule_urlcontainsstring.all()
    urlnotcontainsstring = cr.crawlrule_urlnotcontainsstring.all()

    context = {
            'model': ClassifierModel.objects.get(pk=model_id),
            'models': ClassifierModel.objects.all(),
            'cr': cr,
            'urlcontainsstring': urlcontainsstring,
            'urlnotcontainsstring': urlnotcontainsstring
        }

    template = loader.get_template('ChatEME/CrawlRootDetail.html')
    return HttpResponse(template.render(context, request))
    

def delete_CrawlRoot(request, model_id, cr_id):
    """
    delete one CrawlRoot
    """
    cr = CrawlRoot.objects.get(pk=cr_id)
    cr.delete()

    return redirect ("ChatEME:ClassifierModelDetail", model_id = model_id)


def add_CrawlRule_URLContainsString(request, model_id, cr_id):
    """
    add one CrawRule
    """
    if request.method == 'POST':
        form = CrawlRule_URLContainsStringForm(request.POST)
        if form.is_valid():
            rule = form.save(commit=False)
            rule.crawl_root = CrawlRoot.objects.get(id=
                cr_id)
            rule.save()

            return redirect ("ChatEME:CrawlRootDetail", model_id = model_id, cr_id=cr_id)
      
    form = CrawlRule_URLContainsStringForm()
    return render(request, "ChatEME/generic_model_form.html", {'form':form})


def add_CrawlRule_URLNotContainsString(request, model_id, cr_id):
    """
    add one CrawRule
    """
    if request.method == 'POST':
        form = CrawlRule_URLNotContainsStringForm(request.POST)
        if form.is_valid():
            rule = form.save(commit=False)
            rule.crawl_root = CrawlRoot.objects.get(id=
                cr_id)
            rule.save()

            return redirect ("ChatEME:CrawlRootDetail", model_id = model_id, cr_id=cr_id)
      
    form = CrawlRule_URLNotContainsStringForm()
    return render(request, "ChatEME/generic_model_form.html", {'form':form})


def delete_CrawlRule_URLContainsString(request, model_id, rule_id):
    """
    remove one CrawRule
    """

    rule = get_object_or_404(CrawlRule_URLContainsString, pk=rule_id)

    rule.delete() 

    return redirect ("ChatEME:ClassifierModelDetail", model_id = model_id)


def delete_CrawlRule_URLNotContainsString(request, model_id, rule_id):
    """
    remove one CrawRule
    """

    rule = get_object_or_404(CrawlRule_URLNotContainsString, pk=rule_id)

    rule.delete() 

    return redirect ("ChatEME:ClassifierModelDetail", model_id = model_id)


def apply_rules(request, model_id):
    """
    Applies the CrawlRules to webpages (URLs)
    """
    model = ClassifierModel.objects.get(pk=model_id)

    crawl_roots = model.crawlroots.all()

    for cr in crawl_roots:

        contain_rules = cr.crawlrule_urlcontainsstring.all()

        not_contain_rules = cr.crawlrule_urlnotcontainsstring.all()

        webpages = cr.webpages.all()


        for webpage in webpages:

            for rule in contain_rules:
                if (not rule.apply_rule(webpage.page_url)):
                    webpage.active = False
                    webpage.save()

            for rule in not_contain_rules:
                if (not rule.apply_rule(webpage.page_url)):
                    webpage.active = False

ChatEME/ChatEME/templates/ChatEME/ClassifierModelDetail.html
{% extends 'ChatEME/base.html' %}

{% block content %}

<h1 class="mt-4">{{ model.name }}</h1>

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">{{ model.get_crawl_status }} ({{no_links_processed_webpages}}/{{no_active_webpages}} pages crawled)</li>
    <li class="breadcrumb-item active">{{ model.get_model_builder_status }}</li>
</ol>

Jump to: <br>

<a href="#qa_pairs">QA Pairs</a> - 
<a href="#crawl_roots">Crawl Roots</a> - 
<a href="#crawl_rules">Crawl Rules</a> - 
<a href="#web_pages">Web Pages</a> - 
<a href="#pages_tree_plot">Pages Tree Plot</a><br><br>


{% if web_pages or qapairs %}
<a href="/ChatEME/{{model.id}}/train_model" button class="btn btn-primary" role="button">Build Model</a>
{% endif %}

{% if model.model_exists %}
<a href="/ChatEME/{{model.id}}/inspect_model" button class="btn btn-primary" role="button">Inspect Model</a>
<a href="/ChatEME/{{model.id}}/serve_model" button class="btn btn-primary" role="button">Serve Model</a>
{% endif %}

<a href="/ChatEME/{{model.id}}/import_RasaNLUFile" button class="btn btn-primary" role="button">Import RASA NLU File</a>
<a href="/ChatEME/{{model.id}}/import_RasaDomainFile" button class="btn btn-primary" role="button">Import RASA Domain File</a>
<a href="/ChatEME/{{model.id}}/export_oos2json" button class="btn btn-primary" role="button">Export RASA Out of Scope File</a>

<a id="qa_pairs">
<h2 class="mt-4">QA Pairs</h1>
</a>

<a href="/ChatEME/{{model.id}}/add_QAPair" button class="btn btn-primary" role="button">Add QAPair</a>

<table id="QA Pairs" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Intent</th>
            <th>Answer</th>
            <th>Questions</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for qap in qapairs %}
        <tr>
            <td>{{qap.id}}</td>
            <td>{{qap.intent}}</td>
            <td>{{qap.answer}}</td>
            <td>{{qap.questions }}</td>
            <td>
                <a href="/ChatEME/{{model.id}}/update_QAPair/{{qap.id}}" button class="btn btn-primary" role="button">Edit</a>
                <a href="/ChatEME/{{model.id}}/delete_QAPair/{{qap.id}}" button class="btn btn-primary" role="button">Delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<h2 class="mt-4">Scraper Module</h1>
<a id="crawl_roots">
<h3 class="mt-4">Crawl Roots ({{no_crawl_roots}})</h1>
</a>
<a href="/ChatEME/{{model.id}}/add_CrawlRoot" button class="btn btn-primary" role="button">Add Crawl Root</a>
<table id="Crawl Roots" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Short Name</th>
            <th>Crawl Depth</th>
            <th>Root Url</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for cr in crawl_roots %}
        <tr>
            <td>{{cr.id}}</td>
            <td>{{cr.short_name}}</td>
            <td>{{cr.crawl_depth }}</td>
            <td><a href="{{ cr.root_url}}">{{cr.root_url}}</a></td>
            <td>
                <a href="/ChatEME/{{model.id}}/update_CrawlRoot/{{cr.id}}" button class="btn btn-primary" role="button">Edit</a>
                <a href="/ChatEME/{{model.id}}/delete_CrawlRoot/{{cr.id}}" button class="btn btn-primary" role="button">Delete</a>
                <a href="/ChatEME/{{model.id}}/{{cr.id}}" button class="btn btn-primary" role="button">Add crawl rule</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


<a id="crawl_rules">
<h3 class="mt-4">Crawl Rules ({{no_crawl_rules}})</h1>
</a>

<table id="Crawl Rules" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>Crawl Root</th>
            <th>Type</th>
            <th>Filter String</th>
            <th>Verbose Expression</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for element in urlcontainsstring %}
            {% for rule in element %}
            <tr>
                <td>{{rule.id}}</td>
                <td>{{rule.crawl_root}}</td>
                <td>{{rule.rule_type}}</td>
                <td>{{rule.filter_string}}</td>
                <td>{{rule}}</td>
                <td><a href="/ChatEME/{{model.id}}/{{rule.id}}/delete_CrawlRule_URLContainsString" button class="btn btn-primary" role="button">Delete</a></td>
            </tr>
            {% endfor %}
        {% endfor %}
        {% for element in urlnotcontainsstring %}
            {% for rule in element %}
            <tr>
                <td>{{rule.id}}</td>
                <td>{{rule.crawl_root}}</td>
                <td>{{rule.rule_type}}</td>
                <td>{{rule.filter_string}}</td>
                <td>{{rule}}</td>
                <td><a href="/ChatEME/{{model.id}}/{{rule.id}}/delete_CrawlRule_URLNotContainsString" button class="btn btn-primary" role="button">Delete</a></td>

            </tr>
            {% endfor %}
        {% endfor %}
    </tbody>
</table>

<a id="web_pages">
<h3 class="mt-4">Active Web Pages ({{no_active_webpages}})</h1>
</a>

<a href="/ChatEME/{{model.id}}/crawl_pages" button class="btn btn-primary" role="button">Crawl!</a>
<a href="/ChatEME/{{model.id}}/apply_rules" button class="btn btn-primary" role="button">Apply rules</a>
<a href="/ChatEME/{{model.id}}/clear_pages" button class="btn btn-primary" role="button">Clear pages</a>


<table id="Active Pages" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Title</th>
            <th>Crawl Root</th>
            <th>Parent WebPage</th>
            <th>Crawl Depth</th>
            <th>HTML bytes</th>
            <th>Text Bytes</th>
            <th>URL</th>
            <th>Text/Source</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for page in web_pages %}
        {% if page.active %}
        <tr>
            <td>{{page.get_short_title}}</td>
            <td>{{page.crawl_root}}</td>
            <td>{{page.parent.get_short_title}}</td>
            <td>{{page.crawl_depth}}</td>
            <td>{{page.get_len_html}}</td>
            <td>{{page.get_len_text}}</td>
            <td><a href="{{page.page_url}}">Link</a></td>
            <td><a href="/ChatEME/{{model.id}}/{{page.id}}/page_source">Show</a></td>
            <td>
                <a href="/ChatEME/{{model.id}}/{{page.id}}/flip_active" button class="btn btn-info" role="button">Deactivate</a>
                <a href="/ChatEME/{{model.id}}/update_WebPage/{{page.id}}" button class="btn btn-primary" role="button">Edit</a>
            </td>

        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>

<h3 class="mt-4">Inactive Web Pages</h1>

<table id="Inactive Pages" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Title</th>
            <th>Crawl Root</th>
            <th>Parent WebPage</th>
            <th>Crawl Depth</th>
            <th>HTML bytes</th>
            <th>URL</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for page in web_pages %}
        {% if not page.active %}
        <tr>
            <td>{{page.get_short_title}}</td>
            <td>{{page.crawl_root}}</td>
            <td>{{page.parent.get_short_title}}</td>
            <td>{{page.crawl_depth}}</td>
            <td>{{page.get_len_html}}</td>
            <td><a href="{{page.page_url}}">Link</a></td>
            <td><a href="/ChatEME/{{model.id}}/{{page.id}}/flip_active" button class="btn btn-outline-info" role="button">Activate</a></td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>

<a id="pages_tree_plot">
    
    <h3 class="mt-4">Pages Tree Plot</h1>


    {% autoescape off %}
    {{ plt_div }}
    {% endautoescape %}

</a>
{% endblock %}

ChatEME/ChatEME/templates/ChatEME/ShowPageSource.html
{% extends 'ChatEME/base.html' %}

{% block content %}
<h1 class="mt-4">{{page.get_title}}. <a href="{{page.page_url}}">Show Page</a>
</h1>
<h2 class="mt-4">Extracted Text</h2>

{% autoescape off %}
{{page.display_text}}
{% endautoescape %}

<h2 class="mt-4">Page source</h2>

<pre>{{page.get_html}}</pre>

{% endblock %} 

ChatEME/ChatEME/templates/ChatEME/generic_delete.html
{% extends "ChatEME/base.html" %}

{% block content %}

<div class="col-md-7 mx-auto">

<h1>Delete Item</h1>

<section id = "login" class="gen_form">
<form method="post" class="general_form" > 
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>You cannot undo this action.</p>
    <button type="submit">Delete Item</button>
</form>
</section>
</div>
{% endblock %}

ChatEME/ChatEME/templates/ChatEME/userinput_for_model.html
{% extends 'ChatEME/base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="OK">
</form>

{% if context.qapairs %}

<table id="QAPairs" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Confidence</th>
            <th>Intent</th>
            <th>Answer</th>
            <th>Penalize</th>
        </tr>
    </thead>
    <tbody>
        {% for c, qa in context.qapairs %}
        <tr>
            <td>{{c}}</td>
            <td>{{qa.intent}}</td>
            <td>{{qa.answer}}</td>
            <td><a href="{% url 'ChatEME:penalize_qapair' model_id=context.model_id pair_id=qa.id user_input=context.user_input %}">Penalize</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endif%}

{% if context.pages %}

<table id="Webpages" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Confidence</th>
            <th>Title</th>
            <th>Text/Source</th>
            <th>URL</th>
            <th>Penalize</th>
        </tr>
    </thead>
    <tbody>
        {% for c, page in context.pages %}
        <tr>
            <td>{{c}}</td>
            <td>{{page.get_short_title}}</td>
            <td><a href="/ChatEME/{{context.model_id}}/{{page.id}}/page_source">Show</a></td>
            <td><a href="{{page.page_url}}">Link</a></td>
            <td><a href="{% url 'ChatEME:penalize_webpage' model_id=context.model_id page_id=page.id user_input=context.user_input %}">Penalize</a></td>

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endif%}

{% endblock %}